### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
@jim-minter do you want to review the changes we are bringing in? I didn't see anything that affects us at this point, most interesting is https://github.com/kargakis/acs-engine/pull/10/commits/09f6157f3d263ef302e9534950c959451fa2f66c

**Comment by kargakis** [comment]
`make build` and `make test` pass locally for me.

**Comment by kargakis** [comment]
Still waiting on my subscription. I hope I can test deploying a cluster with this tomorrow.

**Comment by jim-minter** [comment]
@kargakis don't block on me on this, if you think it can go in, merge it :)

**Comment by kargakis** [comment]
I deployed both from master and from this PR and everything was setting up fine but my subscription ID was not working and ansible would die. Still trying to set up a cluster but I think this is fine to push.

**Pull request merged**
