### PR TITLE
disable package_version check in openshift ansible, work around bz1551862

### PR DESCRIPTION
**Pull request by jim-minter**
@kargakis with this PR I am able to build a cluster again...

### CODE REVIEW

**Comment by kargakis** [comment]
@jim-minter thanks, this should help but it's not solving the original problem I am seeing.

/lgtm

**Comment by kargakis** [comment]
https://github.com/kargakis/acs-engine/pull/14 should help debug

**Comment by jim-minter** [comment]
@kargakis still not working after this *merged* ? It must have merged before you try again because it's self-referential when it downloads the updated bastion.sh script from master branch.

**Comment by jim-minter** [comment]
It worked for me 7h ago. I had to change the embedded github user and branch when I was doing my testing for the reason above.

**Comment by kargakis** [comment]
Yeah, I did all that and I also double-checked the playbook in the machine.

**Comment by kargakis** [comment]
Yeah, I did all that and I also double-checked the inventory in the machine.

**Pull request merged**
