### PR TITLE
run auto approver for CSR requests

### PR DESCRIPTION
**Pull request by pweil-**
container built here: https://github.com/pweil-/openshift-autoapprover

fixes https://github.com/kargakis/acs-engine/issues/46

current csr auto approver just checks usernames and, I assume, relies on the fact that the kubeconfigs should be protected for those user names.   Not sure if we want to do something else interesting here, if not this could also fix https://github.com/kargakis/acs-engine/issues/44

### CODE REVIEW

**Comment by jim-minter** [comment]
Clearly this is a required step for being able to add additional nodes to a running cluster post-hoc, but is this the way we want to do it?  I'm not sure that the additional git/docker dependency takes us in the right direction?

**Comment by pweil-** [comment]
> Clearly this is a required step for being able to add additional nodes to a running cluster post-hoc, but is this the way we want to do it

Other suggestions?  Initially we were just approving from the master.sh which is fine if we don't want to go this direction.  I want to make sure that we fit within the existing ansible or are improving it for what we need.

One other suggestion from my side would be bootstrapping the master node or manually configuring it then running the script straight from ansible.

**Comment by pweil-** [comment]
Capturing discussion here:  rather than stealing the auto-approver from ansible and running in a container we are going to investigate pre-accept of master only and running the ansible script once a node is available to run it on.

**Comment by pweil-** [comment]
going to leave the scripting for now.  Our options are:

1.  bootstrap the master special and then run the auto approve stateful set - not better than what is already there
2.  boot the master's node process as a non-bootstrapped node - meh, master is now special again and we have to leave certgen code for nodes
3.  use the upstream auto approver controller - alpha right now

**Pull request closed without merging**
