### PR TITLE
don't use fqdn to connect to etcd, otherwise will fail to accept x.509 certificate

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
@maxamillion you'll need this one

**Comment by maxamillion** [comment]
@jim-minter 👍 thanks!

**Comment by kargakis** [comment]
@maxamillion you need to accept my invite in order to be able to lgtm; I had mentioned that I sent one back when @pweil- asked me to.
permissions

**Pull request merged**
