### PR TITLE
Allow using custom images

### PR DESCRIPTION
**Pull request by kargakis**
@jim-minter @pweil- @kwoodson following https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-mvss-custom-image I am trying to enable use of custom images in our templates.

Trying to figure out a deployment error I am getting:
```
ERRO[0093] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"blobUri\",\r\n    \"message\": \"The URI /subscriptions/27523af7-7c6e-4e06-9d6e-070881f968e8/resourceGroups/opstest/providers/Microsoft.Compute/images/openshift-gi-1520900800 does not look to be correct blob URI.\"\r\n  }\r\n}"}]}} 
```
I am using the full resource path to @kwoodson's image as per the doc. Maybe the blob is not recognized because it comes from a different resource group?
> If you have created the managed disk image beforehand, you should provide the ID of that image instead. This ID must be of the form: `/subscriptions/<subscription-id>resourceGroups/<resource-group-name>/providers/Microsoft.Compute/images/<image-name>`

### CODE REVIEW

**Comment by kargakis** [comment]
> I am using the full resource path to @kwoodson's image as per the doc. Maybe the blob is not recognized because it comes from a different resource group?

OK, that was a mistake in how I was creating the custom image.

**Comment by kwoodson** [comment]
@kargakis, any word on this?

I was manually editing the master|node|infranode json files.
```
       "storageProfile" : {
          "imageReference" : {
              "id": "/subscriptions/<redacted>/resourceGroups/opstest/providers/Microsoft.Compute/images/openshift-gi-1520530616",
              "resource_group" : "opstest"
          },
          "osDisk" : {
```

I recompiled and reattempted my deployment.  This resulted in a noop.  It did not use the image I told it.  Maybe I did something wrong.  I would like to see if yours worked.

**Comment by kargakis** [comment]
Mine fails with a weird API error:
```
ERRO[0088] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadRequest\\\",\\r\\n    \\\"target\\\": \\\"vm.properties.storageProfile.imageReference.id\\\",\\r\\n    \\\"message\\\": \\\"Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 790.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadRequest\\\",\\r\\n    \\\"target\\\": \\\"vm.properties.storageProfile.imageReference.id\\\",\\r\\n    \\\"message\\\": \\\"Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 789.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadRequest\\\",\\r\\n    \\\"target\\\": \\\"vm.properties.storageProfile.imageReference.id\\\",\\r\\n    \\\"message\\\": \\\"Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 790.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"BadRequest\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadRequest\\\",\\r\\n    \\\"target\\\": \\\"vm.properties.storageProfile.imageReference.id\\\",\\r\\n    \\\"message\\\": \\\"Could not find member 'id' on object of type 'PlatformImageReference'. Path 'properties.storageProfile.imageReference.id', line 1, position 793.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}} 
```
The interesting part:
```
\\\"target\\\": \\\"vm.properties.storageProfile.imageReference.id\\\",\\r\\n    \\\"message\\\": \\\"Could not find member 'id' on object of type 'PlatformImageReference'.
```
As per their API docs re [Compute](https://schema.management.azure.com/schemas/2016-04-30-preview/Microsoft.Compute.json) resources, `id` is part of `imageReference`.
```json
    "ImageReference": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Resource Id"
        },
        "publisher": {
          "type": "string",
          "description": "The image publisher."
        },
        "offer": {
          "type": "string",
          "description": "The image offer."
        },
        "sku": {
          "type": "string",
          "description": "The image SKU."
        },
        "version": {
          "type": "string",
          "description": "The image version. The allowed formats are Major.Minor.Build or 'latest'. Major, Minor and Build are decimal numbers. Specify 'latest' to use the latest version of the image."
        }
      },
      "description": "The image reference."
    },
```
Unclear why I am seeing that.

**Comment by kargakis** [comment]
/close

in favor of https://github.com/kargakis/acs-engine/pull/17

**Pull request closed without merging**
