### PR TITLE
remove necessity to specify dummy certificateProfile

### PR DESCRIPTION
**Pull request by jim-minter**

### CODE REVIEW

**Comment by jim-minter** [comment]
WIP because I'm testing it just now

**Comment by jim-minter** [comment]
@kargakis @pweil- what's your take on doing this?

**Comment by pweil-** [comment]
What is our path for custom certificates? Are we going to use these fields, combination of OpenShiftConfig and these, only OpenShiftConfig?

**Comment by jim-minter** [comment]
> What is our path for custom certificates? Are we going to use these fields, combination of OpenShiftConfig and these, only OpenShiftConfig?

I don't know, I think that needs a joint discussion with upstream in due course.  Merging this PR doesn't imply we couldn't using these structs later if appropriate. Having worked this PR through, I think we're better merging it than not: example: it's a good catch to realise that we were populating cloud-init on the non-master VMs when we shouldn't have been.

**Comment by jim-minter** [comment]
did a test deploy; can be merged if appropriate

**Comment by pweil-** [comment]
I don't have any problems with it, per se.  Just a little worried that that section of config is an excellent glaring reminder that we have work to do. :smile:  If something isn't biting me every day I tend to forget about it.

**Comment by jim-minter** [comment]
@pweil- it is already covered by a trello card

**Pull request merged**
