### PR TITLE
Drop some defaulted values from openshift.json

### PR DESCRIPTION
**Pull request by kargakis**
@kwoodson @jim-minter ptal

Fixes https://github.com/kargakis/acs-engine/issues/99

### CODE REVIEW

**Comment by jim-minter** [comment]
/hold

Looks fine to me although demo/demo is still there.

I don't want this change to interfere with the CI work in the last days of the sprint; @kwoodson if it won't feel free to unhold and lgtm; if it will, we'll leave it for next sprint if that's OK

**Comment by kwoodson** [comment]
@jim-minter @kargakis,

This won't interfere with CI at all.  

We are using a programmatic editing tool for the `openshift.json` file.  

Here is where it happens: 
https://github.com/kwoodson/openshift-ansible/blob/azure_provisioning/roles/openshift_azure/tasks/launch.yml#L15

Here is where we define them: 
https://github.com/openshift/release/pull/727/files#diff-988d51b41afc49c86dd79841ecd9f293R45

**Comment by jim-minter** [comment]
@kargakis just a comment on the demo/demo piece then?

**Comment by kargakis** [comment]
> @kargakis just a comment on the demo/demo piece then?

fixed

**Pull request merged**
